const instructorGrid = [
    {
        id: 1,
        img: "assets/images/users/48/avatar-2.jpg",
        name: "Ayaan Bowen",
        total_course: "134",
        email: "ayaanbowen@steex.com",
        designation: "Shopify Development",
        contact: "+(152) 15963 24785",
        rating: "4.5",
        status: "Active",
        experience: "9 Months",
        students: "320",
    }, {
        id: 2,
        img: "assets/images/users/avatar-1.jpg",
        name: "Priscilla Takahashi",
        total_course: "160",
        email: "priscilla@steex.com",
        designation: "Project Manager",
        contact: "+(122) 0397 3076",
        rating: "4.8",
        status: "Active",
        experience: "1 Years",
        students: "159",
    }, {
        id: 3,
        img: "assets/images/users/avatar-3.jpg",
        name: "Martin Roth",
        total_course: "362",
        email: "martinroth@steex.com",
        designation: "Graphic Designer",
        contact: " 781 789 3874",
        rating: "4.3",
        status: "Active",
        experience: "8 Months",
        students: "362",
    }, {
        id: 4,
        img: "assets/images/users/avatar-4.jpg",
        name: "Jennifer Masten",
        total_course: "241",
        email: " jennifermasten@steex.com",
        designation: "React Development",
        contact: "918 664 0738",
        rating: "4.6",
        status: "Active",
        experience: "3 Years",
        students: "321",
    }, {
        id: 5,
        img: "assets/images/users/avatar-5.jpg",
        name: "Hazel Gordon",
        total_course: "237",
        email: "hazelgordon@steex.com",
        designation: "Laravel Development",
        contact: "617 398 3263",
        rating: "4.8",
        status: "Unactive",
        experience: "5 Years",
        students: "364",
    }, {
        id: 6,
        img: "assets/images/users/avatar-8.jpg",
        name: "Michael Johnson",
        total_course: "174",
        email: "michaeljohnson@steex.com",
        designation: "Flask Development",
        contact: "02261 95 80 88",
        rating: "4.7",
        status: "Active",
        experience: "6 Years",
        students: "84",
    }, {
        id: 7,
        img: "assets/images/users/avatar-6.jpg",
        name: "Angela Fryar",
        total_course: "99",
        email: "angelafryar@steex.com",
        designation: "Web Designer",
        contact: " 089 54 77 91",
        rating: "4.9",
        status: "Active",
        experience: "2 Years",
        students: "146",
    }, {
        id: 8,
        img: "assets/images/users/avatar-7.jpg",
        name: "Anthony Gardner",
        total_course: "110",
        email: "anthonygardner@steex.com",
        designation: "Marketing & Management",
        contact: " 09404 91 69 16",
        rating: "4.6",
        status: "Active",
        experience: "7 Months",
        students: "120",
    }, {
        id: 9,
        img: "assets/images/users/avatar-9.jpg",
        name: "James Bradley",
        total_course: "159",
        email: "jamesbradley@steex.com",
        designation: "Marketing & Management",
        contact: "040 67 58 18",
        rating: "4.3",
        status: "Active",
        experience: "1 Years",
        students: "79",
    }, {
        id: 10,
        img: "assets/images/users/avatar-10.jpg",
        name: "Brenda Cornett",
        total_course: "176",
        email: "brendacornett@steex.com",
        designation: "Marketing & Management",
        contact: " 03586 68 04 69",
        rating: "4.3",
        status: "Active",
        experience: "2 Years",
        students: "49",
    }, {
        id: 11,
        img: "assets/images/users/avatar-6.jpg",
        name: "Sarai Schmidt",
        total_course: "320",
        email: "sarai@steex.com",
        designation: "364",
        contact: "+(123) 01592 36544",
        rating: "4.7",
        status: "Active",
        experience: "5 Years",
        students: "364",
    }
]

export { instructorGrid }