const cources = [{
    id: '1',
    img: 'assets/images/learning/react.png',
    postDetail: 'Advanced React And Redux',
    post: 'React Development',
    exLevel: 'Beginner',
    time: '6 Months',
    top: '256',
    lesson: ' 15',
    language: ' English, France',
    price: '$425.36',
    profile: 'assets/images/users/48/avatar-2.jpg',
    name: 'Ayaan Bowen',
    rating: '4.5',
    progresscolor: 'primary',
    progressvalue: 74,
    color: 'info',
    colors: 'success'
},
{
    id: '2',
    img: 'assets/images/learning/laravel.png',
    postDetail: 'Master Laravel For Beginners & Intermediate',
    post: 'Laravel Development',
    exLevel: 'Advance',
    time: '1 Years',
    top: '84',
    lesson: '57',
    language: 'English',
    price: '$264.71',
    profile: 'assets/images/users/48/avatar-6.jpg',
    name: 'Ophelia Steuber',
    rating: '4.8',
    progresscolor: 'warning',
    progressvalue: 53,
    color: 'danger',
    colors: 'info'
},
{
    id: '3',
    img: 'assets/images/learning/core.png',
    postDetail: 'Asp.Net Core 7 True Ultimate Guide',
    post: 'Asp.Net Development',
    exLevel: 'Intermediate',
    time: '8 Years',
    top: '321',
    lesson: '95',
    language: 'English, France',
    price: '$249.99',
    profile: 'assets/images/users/48/avatar-10.jpg',
    name: 'Deondre Huel',
    rating: '4.7',
    progresscolor: 'success',
    progressvalue: 87,
    color: 'primary',
    colors: 'danger'
},
{
    id: '4',
    img: 'assets/images/learning/shopify.png',
    postDetail: 'The Complete Shopify Dropship Course',
    post: 'Shopify Development',
    exLevel: 'Beginner',
    time: '9 Months',
    top: '134',
    lesson: '36',
    language: 'English, France',
    price: '$134.69',
    profile: 'assets/images/users/48/avatar-3.jpg',
    name: 'Nelson Schaden',
    rating: '4.9',
    progresscolor: 'dark',
    progressvalue: 30,
    color: 'success',
    colors: 'success'
}
]

export { cources }